apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
    - 'backend.default.svc.cluster.local'
  http:
    - route:
        - destination:
            host: backend.default.svc.cluster.local
            port:
              number: 80
            subset: v1
          weight: 20
        - destination:
            host: backend.default.svc.cluster.local
            port:
              number: 80
            subset: v2
          weight: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend
spec:
  host: backend.default.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2